name: IMPERFECT HEARTS
favicon: null
layout_spectrum: 0.22052579233422875
typography_spectrum: 0.039365619886666536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5847502322867513
  lightness: 0.004910530522465706
  saturation: 0.47310399380512536
  rhythmicContrast: 0.971898248186335
purpose: []
